---
# - hosts: servers
#   become: yes
#   roles:
#     - server_common
#   tasks:
#     - name: Copy /etc/network/interfaces
#       copy:
#         src: roles/{{ansible_hostname}}/files/interfaces
#         dest: /etc/network/interfaces
#       notify: reload networking

#   handlers:
#     - include: handlers/main.yml
#       static: yes

- hosts: network
  become: yes
  roles:
    - network_common
  tasks:
    - name: Copy /etc/network/interfaces
      copy:
        src: roles/{{ansible_hostname}}/files/interfaces
        dest: /etc/network/interfaces
      notify: reload networking

    - name: Copy Quagga Configuration
      copy:
        src: roles/{{ansible_hostname}}/files/Quagga.conf
        dest: /etc/quagga/Quagga.conf
      notify: reload quagga

  handlers:
    - include: handlers/main.yml
      static: yes
