---
- name: restart quagga
  service:
    name: quagga
    state: restarted

- name: reload networking
  shell: "ifreload -a"

- name: reload quagga
  service:
    name: quagga
    state: reloaded

- name: reboot
  shell: sleep 1 && shutdown -r 0
  poll: 0
  async: 1
  ignore_errors: yes
