---
- name: Verify we are running Cumulus Linux 3.2.0 or later
  fail:
    msg: >
      "Cumulus Linux version is not 3.2.0 or later,
      PIM may not be supported"
  when: ansible_lsb.release[:3]|float >= "3.2"

- name: Copy frr daemons file
  copy:
    src: daemons
    dest: /etc/frr/daemons
  notify: restart frr
